/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chronocell;

import java.awt.Graphics;

/**
 *
 * @author goby
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI(FunctionStructure fct) {
//        f = fct;
        setTitle(fct.name);
        SetFunction(fct);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblXMin = new javax.swing.JLabel();
        lblXMax = new javax.swing.JLabel();
        lblYMax = new javax.swing.JLabel();
        lblYMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        lblXMin.setText("jLabel1");

        lblXMax.setText("jLabel2");

        lblYMax.setText("jLabel3");

        lblYMin.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblYMax)
                    .addComponent(lblYMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblXMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblXMax))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblYMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblYMin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXMin)
                    .addComponent(lblXMax))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(null).setVisible(true);
            }
        });
    }
    FunctionStructure f;
    public void SetFunction(FunctionStructure fct){
        f=fct;
        
//Operators.PrintFunction(fct, "fct", true);
//        Operators.PrintFunction( f,"gui0", false);
    }
    @Override
    public void paint(Graphics g){
        
//        Operators.PrintFunction( f,"gui1", false);
        super.paint(g);
        Graphics gp=jPanel1.getGraphics();
//        double minVal=Operators.GetFunctionMinValue(f);
        double minVal=f.getMinValue();
        double maxVal=f.getMaxValue();
        
         
//        System.out.println("maxval "+maxVal);
//Operators.PrintFunction(f, "f", true);
        int absciss1=0;
        int absciss2=Math.round(jPanel1.getWidth()/(f.maxIndex-f.minIndex+2));
        int ordinate1=(int) Math.round((jPanel1.getHeight()/(minVal-maxVal))*(f.left-maxVal));
        int ordinate2=(int) Math.round(jPanel1.getHeight()/(minVal-maxVal)*(f.values[0]-maxVal));
        gp.drawLine(absciss1,ordinate1, absciss2,ordinate2);
        for (int i=f.minIndex;i<=f.maxIndex-1;i++){
            absciss1=(int) Math.round((i+1-f.minIndex)*jPanel1.getWidth()/(f.maxIndex-f.minIndex+2));
            absciss2=(int) Math.round((i+1-f.minIndex+1)*jPanel1.getWidth()/(f.maxIndex-f.minIndex+2));
            ordinate1=(int) Math.round((jPanel1.getHeight()/(minVal-maxVal))*(f.values[i]-maxVal));
            ordinate2=(int) Math.round(jPanel1.getHeight()/(minVal-maxVal)*(f.values[i+1]-maxVal));
            gp.drawLine(absciss1,ordinate1, absciss2,ordinate2);
        }
        absciss1=(int) Math.round((f.maxIndex+1-f.minIndex)*jPanel1.getWidth()/(f.maxIndex-f.minIndex+2));
        absciss2=(int) Math.round((f.maxIndex+1-f.minIndex+1)*jPanel1.getWidth()/(f.maxIndex-f.minIndex+2));
        ordinate1=(int) Math.round((jPanel1.getHeight()/(minVal-maxVal))*(f.values[f.maxIndex]-maxVal));
        ordinate2=(int) Math.round(jPanel1.getHeight()/(minVal-maxVal)*(f.right-maxVal));
        gp.drawLine(absciss1,ordinate1, absciss2,ordinate2);
        lblXMin.setText((new Double(f.min-f.step)).toString());
        lblXMax.setText((new Double(f.max+f.step)).toString());
        lblYMin.setText((new Double(minVal)).toString());
        lblYMax.setText((new Double(maxVal)).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblXMax;
    private javax.swing.JLabel lblXMin;
    private javax.swing.JLabel lblYMax;
    private javax.swing.JLabel lblYMin;
    // End of variables declaration//GEN-END:variables
}
